[package]
name = "cloud"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.20"
byteorder = "1"
chrono = "0.4"
core = { path = "../core" }
ssh-key = { version = "0.5", features = ["ed25519", "getrandom"] }

[dev-dependencies]
rand_core = "0.6" 
tempfile = "3.3"
