name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: box/src/box.rs
          UPLOAD_MODE: none

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
